### ISSUE TITLE
How to add new icons and contribute ?

### ISSUE THREAD

**Issue by StarAzure** [webkul/vivid#15]
Hello,
I would like to design and add new icons and use it/contribute. Any documentation to do so will help. 

Thanks

**Comment by nitishkmrk** [comment]
We are currently not accepting pull requests for icons.

**Comment by StarAzure** [comment]
Understood but how can we add our own icons for our own needs ? Do you have any documentation ? 
Requesting new icons and having you implement at your discretion and time may not work for many of us as you only have a small number of icons. If we could add our own, it will make it super useful.

**Comment by nitishkmrk** [comment]
@StarAzure We're still working on Icons. However if you wish to customise the icons, Follow Steps below - 
1. Replace the Icons in `icons` directory
2. Make sure SVG Icons has the `vi-primary` and `vi-accent` class, so that the colors be customized from `src/config.js`.
3. Run `npm run build`
**Documentation is coming soon. Project is still growing.
Thanks!
